//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingId { get; set; }
        public int UserId { get; set; }
        public int MealId { get; set; }
        public int Mark { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual User User { get; set; }
    }
}
